[BitTorrent]
Session\DefaultSavePath=/music/books/mam/
Session\TempPathEnabled=false
Session\Port=58123
Session\GlobalMaxRatio=-1
Session\GlobalMaxSeedingMinutes=-1
Session\GlobalMaxInactiveSeedingMinutes=-1
Session\QueueingSystemEnabled=false
Session\DHTEnabled=false
Session\PeXEnabled=false
Session\LSDEnabled=false
Session\AnonymousModeEnabled=false

[Preferences]
General\Locale=en
WebUI\Address=*
WebUI\Port=8081
WebUI\LocalHostAuth=false
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\HTTPS\Enabled=false
